ifeq (Kasama,$(shell hostname))
	DESIRED_TARGET := cmstorm-tk.kbd
else
	DESIRED_TARGET := $(shell hostname).kbd
endif
DESIRED_TARGET := cmstorm-tk.kbd

BASE_FILES = aliases.kbd
TARGET_FILE = config-cmstorm.kbd

.PHONY: all

all: $(TARGET_FILE)

$(TARGET_FILE): $(BASE_FILES)
	@echo "Building $(TARGET_FILE) with $(DESIRED_TARGET)"
	@echo ";; THIS FILE WAS AUTOMATICALLY GENERATED BY MAKE - DO NOT EDIT DIRECTLY" > $(TARGET_FILE)
	@echo ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;" >> $(TARGET_FILE)
	@cat $(BASE_FILES) $(DESIRED_TARGET) >> $(TARGET_FILE)

clean:
	@echo "Removing $(TARGET_FILE)"
	@rm $(TARGET_FILE)
